In [17]:
pip install gensim

                                              0.0/23.9 MB ? eta -:--:--
                                              0.4/23.9 MB 12.5 MB/s eta 0:00:02
     -                                        1.1/23.9 MB 14.0 MB/s eta 0:00:02
     --                                       1.6/23.9 MB 13.0 MB/s eta 0:00:02
     ----                                     2.6/23.9 MB 15.2 MB/s eta 0:00:02
     -----                                    3.6/23.9 MB 16.2 MB/s eta 0:00:02
     -------                                  4.4/23.9 MB 16.6 MB/s eta 0:00:02
     --------                                 5.4/23.9 MB 17.2 MB/s eta 0:00:02
     -----------                              6.7/23.9 MB 18.5 MB/s eta 0:00:01
     -------------                            8.0/23.9 MB 19.7 MB/s eta 0:00:01
     ----------------                         9.9/23.9 MB 21.7 MB/s eta 0:00:01
     ------------------                      11.6/23.9 MB 26.2 MB/s eta 0:00:01
     ----------------------                  13.


[notice] A new release of pip is available: 23.1.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd 
import numpy as np 
import spacy 
import gensim

In [102]:
df = pd.read_csv('../base/pre_processamento.csv', index_col=0)


In [103]:
df 

autor   
dataPublicada                                     
"2022-03-04 08:36:00"                lmviapiana  \
"2022-03-03 21:10:00"              vanilson_dos   
"2022-03-03 20:54:00"               ricktolledo   
"2022-03-03 18:56:00"          claudiofalavinha   
"2022-03-03 16:11:00"     paularodrigues.invest   
...                                         ...   
"2022-11-30 07:48:00"  perspectiveinvestimentos   
"2022-11-30 08:42:00"              marlenenelso   
"2022-11-30 11:27:00"            eduardocolares   
"2022-11-30 12:18:00"             jayipacderota   
"2022-11-30 14:27:00"                 bfmarilia   

                                                                   texto   
dataPublicada                                                              
"2022-03-04 08:36:00"                               Minuto touro de ouro  \
"2022-03-03 21:10:00"                                   @ricktolledo Sim   
"2022-03-03 20:54:00"  Queria saber se a Btg banking é a própria btg ...   
"2022-03-03 18:56:00"                                     @thaotinhasbfc   
"2022-03-03 16:11:00"                                               👏👏👏👏   
...                                                                  ...   
"2022-11-30 07:48:00"                               Excelente explicação   
"2022-11-30 08:42:00"  Porque  o brg tá  diminuído  o limite  do cart...   
"2022-11-30 11:27:00"               Atendam o telefone pelo amor de Deus   
"2022-11-30 12:18:00"  Estou muito grato por todo o esforço que você ...   
"2022-11-30 14:27:00"  @btgpactual pq o morning call não está mais ap...   

                      sentimento tipoInteracao  anomalia   
dataPublicada                                              
"2022-03-04 08:36:00"   POSITIVE    comentário         0  \
"2022-03-03 21:10:00"    NEUTRAL      resposta         0   
"2022-03-03 20:54:00"   POSITIVE    comentário         0   
"2022-03-03 18:56:00"    NEUTRAL    comentário         0   
"2022-03-03 16:11:00"    NEUTRAL    comentário         0   
...                          ...           ...       ...   
"2022-11-30 07:48:00"   POSITIVE    comentário         0   
"2022-11-30 08:42:00"   NEGATIVE    comentário         1   
"2022-11-30 11:27:00"   POSITIVE    comentário         0   
"2022-11-30 12:18:00"   POSITIVE    comentário         1   
"2022-11-30 14:27:00"   NEGATIVE    comentário         0   

                       probabilidadeAnomalia   
dataPublicada                                  
"2022-03-04 08:36:00"                     38  \
"2022-03-03 21:10:00"                     17   
"2022-03-03 20:54:00"                     20   
"2022-03-03 18:56:00"                     41   
"2022-03-03 16:11:00"                     15   
...                                      ...   
"2022-11-30 07:48:00"                     15   
"2022-11-30 08:42:00"                     53   
"2022-11-30 11:27:00"                     28   
"2022-11-30 12:18:00"                     52   
"2022-11-30 14:27:00"                     28   

                                                                linkPost   
dataPublicada                                                              
"2022-03-04 08:36:00"  https://www.instagram.com/p/CapXhB5Lvas/#17977...  \
"2022-03-03 21:10:00"  https://www.instagram.com/p/CapXhB5Lvas/#17842...   
"2022-03-03 20:54:00"  https://www.instagram.com/p/CapXhB5Lvas/#17935...   
"2022-03-03 18:56:00"  https://www.instagram.com/p/CapXhB5Lvas/#17942...   
"2022-03-03 16:11:00"  https://www.instagram.com/p/CaptWrtOT8U/#17943...   
...                                                                  ...   
"2022-11-30 07:48:00"  https://www.instagram.com/p/ClgWR-Ov2H1/#18001...   
"2022-11-30 08:42:00"  https://www.instagram.com/p/ClgWR-Ov2H1/#17878...   
"2022-11-30 11:27:00"  https://www.instagram.com/p/CllkSBOuKlJ/#17960...   
"2022-11-30 12:18:00"  https://www.instagram.com/p/CllkSBOuKlJ/#17960...   
"2022-11-30 14:27:00"  https://www.instagram.com/p/CllkSBOuKlJ/#17975..

*1* - Baixe o modelo treinado de word embedding "CBOW 50 dimensões" do site do NILC (http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc)

2 - Coloque o arquivo extraído "cbow_s50.txt" na mesma pasta no drive deste notebook

3 - Monte o drive no menu à esquerda

4 - Ache o arquivo e nas opções escolha "copiar caminho". Cole na célular de código abaixo.

In [4]:
cbow = '../base/cbow_s50.txt'


In [112]:
from scipy.spatial.distance import cosine

from gensim.models import KeyedVectors

model_cbow = KeyedVectors.load_word2vec_format(cbow)

In [113]:
# Testando o word2vec
wordvec_word1 = model_cbow['banco']

wordvec_word1

array([ 1.81041e-01,  1.07700e-01, -1.04667e-01,  2.43361e-01,
        6.06380e-02,  3.92829e-01, -3.33944e-01, -3.81778e-01,
        1.42200e-01,  8.59360e-02, -1.16615e-01,  3.95722e-01,
       -6.12684e-01, -7.68980e-02,  3.34396e-01,  8.11270e-02,
       -5.17700e-02, -3.21950e-01, -6.91509e-01, -3.31210e-01,
       -5.43213e-01,  6.09881e-01,  2.43700e-01,  3.73240e-02,
        1.16518e-01,  1.78859e-01, -3.78839e-01,  1.27430e-01,
        1.94497e-01,  7.32000e-04,  3.14395e-01, -2.04550e-01,
        5.34431e-01, -5.55100e-03,  3.52343e-01, -4.92000e-02,
       -1.38384e-01,  2.31630e-02, -3.40013e-01,  5.00201e-01,
       -1.14170e-02, -1.29925e-01, -6.12800e-03, -1.80481e-01,
        1.99391e-01,  1.37645e-01, -7.66434e-01, -2.26784e-01,
       -6.16110e-02,  9.05920e-02], dtype=float32)

In [197]:
def word2vec(tokenized_test):
    array_full = []
    for x in tokenized_test:
        vector = model_cbow[x]
        array_full.append(vector)
    final_output = sum(array_full)  
    return final_output
        


In [198]:
df['veczada'] = df['texto_tokenizado'].apply(word2vec)


KeyError: "Key ' ' not present"

In [186]:
df.head(5)

autor   
dataPublicada                                  
"2022-03-04 08:36:00"             lmviapiana  \
"2022-03-03 21:10:00"           vanilson_dos   
"2022-03-03 20:54:00"            ricktolledo   
"2022-03-03 18:56:00"       claudiofalavinha   
"2022-03-03 16:11:00"  paularodrigues.invest   

                                                                   texto   
dataPublicada                                                              
"2022-03-04 08:36:00"                               Minuto touro de ouro  \
"2022-03-03 21:10:00"                                   @ricktolledo Sim   
"2022-03-03 20:54:00"  Queria saber se a Btg banking é a própria btg ...   
"2022-03-03 18:56:00"                                     @thaotinhasbfc   
"2022-03-03 16:11:00"                                               👏👏👏👏   

                      sentimento tipoInteracao  anomalia   
dataPublicada                                              
"2022-03-04 08:36:00"   POSITIVE    comentário         0  \
"2022-03-03 21:10:00"    NEUTRAL      resposta         0   
"2022-03-03 20:54:00"   POSITIVE    comentário         0   
"2022-03-03 18:56:00"    NEUTRAL    comentário         0   
"2022-03-03 16:11:00"    NEUTRAL    comentário         0   

                       probabilidadeAnomalia   
dataPublicada                                  
"2022-03-04 08:36:00"                     38  \
"2022-03-03 21:10:00"                     17   
"2022-03-03 20:54:00"                     20   
"2022-03-03 18:56:00"                     41   
"2022-03-03 16:11:00"                     15   

                                                                linkPost   
dataPublicada                                                              
"2022-03-04 08:36:00"  https://www.instagram.com/p/CapXhB5Lvas/#17977...  \
"2022-03-03 21:10:00"  https://www.instagram.com/p/CapXhB5Lvas/#17842...   
"2022-03-03 20:54:00"  https://www.instagram.com/p/CapXhB5Lvas/#17935...   
"2022-03-03 18:56:00"  https://www.instagram.com/p/CapXhB5Lvas/#17942...   
"2022-03-03 16:11:00"  https://www.instagram.com/p/CaptWrtOT8U/#17943...   

                       processado  contemHyperlink   
dataPublicada                                        
"2022-03-04 08:36:00"           0                0  \
"2022-03-03 21:10:00"           0                0   
"2022-03-03 20:54:00"           0                0   
"2022-03-03 18:56:00"           0                0   
"2022-03-03 16:11:00"           0                0   

                                                         texto_e_palavra   
dataPublicada                                                              
"2022-03-04 08:36:00"                               Minuto touro de ouro  \
"2022-03-03 21:10:00"                                   @ricktolledo Sim   
"2022-03-03 20:54:00"  Queria saber se a Btg banking é a própria btg ...   
"2022-03-03 18:56:00"                                     @thaotinhasbfc   
"2022-03-03 16:11:00"                       palmas palmas palmas palmas    

                                                texto_tokenizado   
dataPublicada                                                      
"2022-03-04 08:36:00"                ['minuto', 'touro', 'ouro']  \
"2022-03-03 21:10:00"                                    ['sim']   
"2022-03-03 20:54:00"  ['queria', 'saber', 'banking', 'própria']   
"2022-03-03 18:56:00"                                         []   
"2022-03-03 16:11:00"   ['palmas', 'palmas', 'palmas', 'palmas']   

                                                                 veczada  
dataPublicada                                                             
"2022-03-04 08:36:00"  [[-0.403823, 0.240759, 0.44289, -0.570807, 0.1...  
"2022-03-03 21:10:00"  [[-0.403823, 0.240759, 0.44289, -0.570807, 0.1...  
"2022-03-03 20:54:00"  [[-0.403823, 0.240759, 0.44289, -0.570807, 0.1...  
"2022-03-03 18:56:00"  [[-0.403823, 0.240759, 0.44289, -0.570807, 0.1...  
"2022-03-03 16:11:00"  [[-0.403823, 0.2

In [199]:
oi = ['teste','btg','ouro']
teste = word2vec(oi)
teste

array([ 0.777123  , -0.15518099, -0.748456  ,  0.812582  ,  0.8782921 ,
        1.799677  , -0.739415  ,  0.141588  ,  0.247675  ,  1.453151  ,
       -0.66966194,  0.698563  , -1.780744  ,  0.356594  ,  0.909181  ,
       -0.22772798, -0.567463  , -0.462222  , -0.723231  , -0.221801  ,
       -0.617952  ,  1.7158461 ,  0.510006  ,  0.649718  ,  0.99031603,
       -0.885517  , -0.178323  ,  0.433119  , -0.46985298,  0.139401  ,
        0.293711  , -0.012453  ,  0.300223  , -0.42216   ,  0.12107903,
        0.644521  ,  0.30552   ,  0.219815  , -0.08423398,  0.875046  ,
        0.34490198,  0.02951699,  0.5438701 ,  0.345855  ,  0.75601006,
       -0.236267  , -0.972637  ,  0.318803  , -0.50994   ,  0.684855  ],
      dtype=float32)

In [200]:
oito = ['teste']
tes = word2vec(oito)
tes

array([ 0.066184, -0.241351,  0.074098,  0.095256,  0.328815,  0.444887,
        0.212839,  0.226351,  0.266563,  0.538785, -0.107048,  0.264954,
       -0.412093,  0.079404,  0.45781 ,  0.2443  , -0.19329 ,  0.042285,
       -0.027314,  0.175035, -0.319714,  0.488565, -0.031984,  0.312068,
        0.427231, -0.02192 ,  0.093675, -0.252333, -0.107619, -0.02222 ,
        0.099248,  0.123382,  0.464005, -0.138848,  0.100047,  0.420187,
        0.159133, -0.261898,  0.041417,  0.474442,  0.083101, -0.168923,
        0.256974, -0.327491,  0.445466, -0.001271, -0.014991,  0.067393,
       -0.295427,  0.058224], dtype=float32)

In [117]:
testinho = word2vec(df['texto_tokenizado'])

TypeError: 'KeyedVectors' object is not callable

In [ ]:
# Criando uma função que rode em todo o dataframe 
df['word_2_vec'] = df['texto_e_palavra'].apply(tokenizeWords)
